services:
  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # بخش حیاتی برای اطمینان از بالا آمدن دیتابیس
    depends_on:
      - postgres_db 

  postgres_db:
    # ... بقیه کد مربوط به postgres_db